# Generated by Django 2.2.3 on 2019-07-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudview',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crud_views', to='terra_geocrud.CrudGroupView'),
        ),
        migrations.AlterField(
            model_name='crudview',
            name='layer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crud_view', to='geostore.Layer'),
        ),
    ]
