# Generated by Django 2.1.10 on 2019-07-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0002_auto_20190723_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudgroupview',
            name='pictogram',
            field=models.ImageField(blank=True, null=True, upload_to='crud/groups/pictograms'),
        ),
    ]
