# Generated by Django 2.1.10 on 2019-07-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0003_auto_20190724_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudgroupview',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='crudview',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
