# Generated by Django 2.1.10 on 2019-07-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0006_auto_20190725_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudview',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crud_views', to='terra_geocrud.CrudGroupView'),
        ),
    ]
