# Generated by Django 2.1.12 on 2019-09-13 13:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0011_auto_20190902_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudview',
            name='ui_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/'),
        ),
    ]
