# Generated by Django 2.2.5 on 2019-09-27 09:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0012_auto_20190913_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePropertyDisplayGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('pictogram', models.ImageField(blank=True, null=True, upload_to='crud/feature_display_group/pictograms')),
                ('properties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None)),
                ('crud_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_display_groups', to='terra_geocrud.CrudView')),
            ],
            options={
                'verbose_name': 'Display Group',
                'verbose_name_plural': 'Display Groups',
                'ordering': ('label',),
            },
        ),
    ]
