# Generated by Django 2.2.5 on 2019-09-27 12:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0013_featurepropertydisplaygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepropertydisplaygroup',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featurepropertydisplaygroup',
            name='properties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=list, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='featurepropertydisplaygroup',
            unique_together={('crud_view', 'slug'), ('crud_view', 'label')},
        ),
    ]
