# Generated by Django 2.2.5 on 2019-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0015_auto_20190927_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepropertydisplaygroup',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
