# Generated by Django 2.2.5 on 2019-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0016_auto_20190927_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepropertydisplaygroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
