# Generated by Django 2.2.5 on 2019-09-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0017_featurepropertydisplaygroup_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurepropertydisplaygroup',
            options={'ordering': ('order', 'label'), 'verbose_name': 'Display Group', 'verbose_name_plural': 'Display Groups'},
        ),
    ]
