# Generated by Django 2.2.5 on 2019-09-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0022_auto_20190928_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudgroupview',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Order entry in left menu'),
        ),
        migrations.AlterField(
            model_name='crudview',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Order entry in left menu'),
        ),
        migrations.AlterField(
            model_name='featurepropertydisplaygroup',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
