# Generated by Django 2.2.6 on 2019-10-17 13:51

from django.db import migrations, models
import sorl.thumbnail.fields
import terra_geocrud.models
from terra_geocrud.properties.files import get_storage


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0027_attachmentcategory_featureattachment_featurepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureattachment',
            name='file',
            field=models.FileField(storage=get_storage(), upload_to=terra_geocrud.models.feature_attachment_directory_path),
        ),
        migrations.AlterField(
            model_name='featurepicture',
            name='image',
            field=sorl.thumbnail.fields.ImageField(storage=get_storage(), upload_to=terra_geocrud.models.feature_attachment_directory_path),
        ),
    ]
