# Generated by Django 2.2.6 on 2019-10-17 14:27

import django.core.files.storage
from django.db import migrations
import sorl.thumbnail.fields
import terra_geocrud.models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0028_auto_20191017_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepicture',
            name='image',
            field=sorl.thumbnail.fields.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=terra_geocrud.models.feature_picture_directory_path),
        ),
    ]
