# Generated by Django 2.2.6 on 2019-10-17 14:27

from django.db import migrations
import sorl.thumbnail.fields
import terra_geocrud.models
from terra_geocrud.properties.files import get_storage


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0028_auto_20191017_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepicture',
            name='image',
            field=sorl.thumbnail.fields.ImageField(storage=get_storage(), upload_to=terra_geocrud.models.feature_picture_directory_path),
        ),
    ]
