# Generated by Django 2.2.6 on 2019-11-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0029_auto_20191017_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydisplayrendering',
            name='widget',
            field=models.CharField(choices=[('terra_geocrud.properties.widgets.ArrayObjectTableWidget', 'ArrayObjectTableWidget'), ('terra_geocrud.properties.widgets.DataUrlToImgWidget', 'DataUrlToImgWidget'), ('terra_geocrud.properties.widgets.DateFormatWidget', 'DateFormatWidget'), ('terra_geocrud.properties.widgets.FileAhrefWidget', 'FileAhrefWidget')], max_length=255),
        ),
    ]
