# Generated by Django 2.2.7 on 2019-11-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0030_auto_20191104_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crudview',
            options={'ordering': ('order',), 'verbose_name': 'View', 'verbose_name_plural': 'Views'},
        ),
    ]
