# Generated by Django 2.2.7 on 2019-11-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0031_auto_20191105_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudview',
            name='visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Keep visible if ungrouped.'),
        ),
    ]
