# Generated by Django 2.2.7 on 2019-11-22 17:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0033_featureextrageom_layerextrageom'),
        ('terra_geocrud', '0032_crudview_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraLayerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_style', django.contrib.postgres.fields.jsonb.JSONField(help_text='Custom mapbox style for this entry')),
                ('crud_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_layer_style', to='terra_geocrud.CrudView')),
                ('layer_extra_geom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='geostore.LayerExtraGeom')),
            ],
            options={
                'verbose_name': 'ExtraLayer style',
                'verbose_name_plural': 'ExtraLayer styles',
                'unique_together': {('crud_view', 'layer_extra_geom')},
            },
        ),
    ]
