# Generated by Django 2.2.8 on 2019-12-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0035_auto_20191204_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crudview',
            options={'ordering': ('group', 'order'), 'verbose_name': 'View', 'verbose_name_plural': 'Views'},
        ),
    ]
