# Generated by Django 3.0.4 on 2020-03-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0037_crudview_name_plural'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyDisplayRendering',
        ),
    ]
