# Generated by Django 2.2.9 on 2020-01-28 14:14

from django.db import migrations, models
import django.db.models.deletion


def move_data_feature_title_property(apps, schema_editor):
    # We can't import Layer models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    CrudView = apps.get_model('terra_geocrud', 'CrudView')
    SchemaObject = apps.get_model('geostore', 'LayerSchemaProperty')
    for view in CrudView.objects.all():
        if view.feature_title_property:
            view.feature_title_property2 = SchemaObject.objects.get(layer=view.layer, slug=view.feature_title_property)
            view.save()


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0037_move_data_default_list_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudview',
            name='feature_title_property2',
            field=models.ForeignKey(blank=True, help_text='Schema property used to define feature title.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='geostore.LayerSchemaProperty'),
        ),
        migrations.RunPython(move_data_feature_title_property),
        migrations.RemoveField(
            model_name='crudview',
            name='feature_title_property',
        ),
        migrations.RenameField(
            model_name='crudview',
            old_name='feature_title_property2',
            new_name='feature_title_property',
        ),
    ]
