# Generated by Django 3.0.4 on 2020-03-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0039_auto_20200320_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudview',
            name='object_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
