# Generated by Django 3.0.4 on 2020-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0040_crudview_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudview',
            name='object_name',
            field=models.CharField(blank=True, default='', help_text='Singular object designation', max_length=100),
        ),
        migrations.AlterField(
            model_name='crudview',
            name='object_name_plural',
            field=models.CharField(blank=True, default='', help_text='Plural object designation', max_length=100),
        ),
    ]
