# Generated by Django 3.0.4 on 2020-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0042_auto_20200402_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudviewproperty',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
