# Generated by Django 3.0.4 on 2020-04-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0044_auto_20200402_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crudviewproperty',
            options={'ordering': ('view', 'group', 'order')},
        ),
        migrations.RemoveField(
            model_name='featurepropertydisplaygroup',
            name='properties',
        ),
        migrations.AddField(
            model_name='crudview',
            name='new_default_list_properties',
            field=models.ManyToManyField(blank=True, related_name='used_by_list', to='terra_geocrud.CrudViewProperty'),
        ),
        migrations.AddField(
            model_name='crudview',
            name='new_feature_title_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_title', to='terra_geocrud.CrudViewProperty'),
        ),
    ]
