# Generated by Django 3.0.4 on 2020-04-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0046_auto_20200402_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudview',
            name='default_list_properties',
        ),
        migrations.RemoveField(
            model_name='crudview',
            name='feature_title_property',
        ),
        migrations.AlterField(
            model_name='crudview',
            name='new_feature_title_property',
            field=models.ForeignKey(help_text='Schema property used to define feature title.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_title', to='terra_geocrud.CrudViewProperty'),
        ),
    ]
