# Generated by Django 3.0.4 on 2020-04-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0047_auto_20200402_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crudview',
            old_name='new_default_list_properties',
            new_name='default_list_properties',
        ),
    ]
