# Generated by Django 3.0.5 on 2020-04-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0050_auto_20200402_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureattachment',
            options={'ordering': ('feature', 'category', '-created_at'), 'verbose_name': 'Feature attachment', 'verbose_name_plural': 'Feature attachments'},
        ),
        migrations.AlterModelOptions(
            name='featurepicture',
            options={'ordering': ('feature', 'category', '-created_at'), 'verbose_name': 'Feature picture', 'verbose_name_plural': 'Feature pictures'},
        ),
        migrations.AlterField(
            model_name='crudviewproperty',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_properties', to='terra_geocrud.FeaturePropertyDisplayGroup'),
        ),
    ]
