# Generated by Django 3.0.5 on 2020-04-20 09:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import terra_geocrud.validators


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0052_auto_20200420_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudviewproperty',
            name='json_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[terra_geocrud.validators.validate_schema_property]),
        ),
    ]
