# Generated by Django 3.0.6 on 2020-05-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0053_auto_20200420_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudview',
            name='default_list_properties',
            field=models.ManyToManyField(blank=True, help_text='Schema properties used in API list by default.', related_name='used_by_list', to='terra_geocrud.CrudViewProperty'),
        ),
        migrations.AlterField(
            model_name='crudview',
            name='feature_title_property',
            field=models.ForeignKey(blank=True, help_text='Schema property used to define feature title.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_title', to='terra_geocrud.CrudViewProperty'),
        ),
    ]
