# Generated by Django 3.0.6 on 2020-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0054_auto_20200525_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentcategory',
            name='pictogram',
            field=models.ImageField(blank=True, null=True, upload_to='terra_geocrud/attachments_categories/pictograms'),
        ),
        migrations.AlterField(
            model_name='crudgroupview',
            name='pictogram',
            field=models.ImageField(blank=True, help_text='Picto displayed in left menu', null=True, upload_to='terra_geocrud/groups/pictograms'),
        ),
        migrations.AlterField(
            model_name='crudview',
            name='pictogram',
            field=models.ImageField(blank=True, help_text='Picto displayed in left menu', null=True, upload_to='terra_geocrud/views/pictograms'),
        ),
        migrations.AlterField(
            model_name='featurepropertydisplaygroup',
            name='pictogram',
            field=models.ImageField(blank=True, null=True, upload_to='terra_geocrud/property_groups/pictograms'),
        ),
    ]
