# Generated by Django 3.1.2 on 2020-10-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0058_propertyenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudviewproperty',
            name='include_in_tile',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='crudviewproperty',
            name='required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='propertyenum',
            name='value',
            field=models.CharField(help_text='Value should always be casted in property type.', max_length=250),
        ),
    ]
