# Generated by Django 3.1.5 on 2021-01-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0060_auto_20210122_1132'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routingsettings',
            name='check_provider_layer',
        ),
        migrations.RemoveConstraint(
            model_name='routingsettings',
            name='check_provider_mapbox_transit',
        ),
        migrations.AddConstraint(
            model_name='routingsettings',
            constraint=models.UniqueConstraint(condition=models.Q(layer__isnull=False), fields=('provider', 'layer', 'crud_view'), name='check_provider_layer'),
        ),
        migrations.AddConstraint(
            model_name='routingsettings',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, mapbox_transit=''), fields=('provider', 'mapbox_transit', 'crud_view'), name='check_provider_mapbox_transit'),
        ),
    ]
