# Generated by Django 3.1.6 on 2021-02-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0061_auto_20210122_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudviewproperty',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
