# Generated by Django 3.1.6 on 2021-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0062_crudviewproperty_editable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='crudviewproperty',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('editable', True), ('required', True)), models.Q(('editable', True), ('required', False)), models.Q(('editable', False), ('required', False)), _connector='OR'), name='check_required_editable'),
        ),
    ]
