# Generated by Django 3.1.6 on 2021-02-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geostore', '0044_auto_20201106_1638'),
        ('terra_geocrud', '0063_auto_20210204_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingInformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_description', models.JSONField(blank=True, default=dict)),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routing_information', to='geostore.feature')),
            ],
        ),
    ]
