# Generated by Django 3.1.6 on 2021-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0063_auto_20210204_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudviewproperty',
            name='function_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='crudviewproperty',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('editable', True), ('function_path', '')), models.Q(('editable', False), ('function_path', '')), models.Q(('editable', False), models.Q(_negated=True, function_path='')), _connector='OR'), name='check_function_path_not_editable'),
        ),
    ]
