# Generated by Django 3.1.6 on 2021-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0063_auto_20210204_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudviewproperty',
            name='func',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='crudviewproperty',
            constraint=models.CheckConstraint(check=models.Q(('editable', False), ('func', ''), _negated=True), name='check_func_not_editable'),
        ),
    ]
