# Generated by Django 3.1.6 on 2021-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0064_routinginformations'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudviewproperty',
            name='function_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
