# Generated by Django 3.1.7 on 2021-06-18 09:01

from django.db import migrations, models
import terra_geocrud.validators


class Migration(migrations.Migration):

    dependencies = [
        ('terra_geocrud', '0065_auto_20210218_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudviewproperty',
            name='function_path',
            field=models.CharField(blank=True, max_length=255, validators=[terra_geocrud.validators.validate_function_path]),
        ),
    ]
