dist: bionic

sudo: required

language: python

python:
- '3.6'
- '3.7'

services:
- postgresql

addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10-postgis-2.4

stages:
- lint
- test
- deploy

install:
- sudo apt-get -y install libproj-dev binutils gdal-bin
- pip install -e .[dev]
- pip install codecov

before_script:
- psql -c "CREATE USER travis_ci_test WITH ENCRYPTED PASSWORD 'travis_ci_test';" -U
  postgres
- psql -c "ALTER USER travis_ci_test WITH SUPERUSER;" -U postgres
- psql -c 'CREATE DATABASE travis_ci_test WITH OWNER travis_ci_test;' -U postgres
- psql -d travis_ci_test -c 'CREATE EXTENSION postgis;'
#- psql -d travis_ci_test -c 'CREATE EXTENSION pgrouting;'

after_failure:
- pip freeze

script:
- coverage run ./manage.py test --settings=test_terra_geocrud.settings

after_script:
  - codecov

jobs:
  include:
  - stage: lint
    before_script: skip
    install:
    - pip install flake8
    script:
    - flake8 terra_geocrud
    after_script: skip
    after_failure: skip
  - stage: deploy
    install: skip
    before_script: skip
    script: skip
    after_script: skip
    deploy:
      stage: deploy
      provider: pypi
      user: __token__
      password:
        secure: j9fdiMDpjthZN4dhAcGSqFQWuGWPpa5cJmRy50F57G/WXmE76IWLiR/Fagg/acRmclBDfHgN+0y8v6jd64J9/gwpRqKs5Z8jArevjL13zxpkTyP9COSq9Pw5B7to/htwEl9KEBMInHIT/240UGxOj8THSMqPiBTYL5T4k6u6rzYtCcGT0kDeBLdIyTl2fYs31/EeCd941F8OCC+LstOzBiM7A3ISCEubDWYsqnvypYMBFqdlZThC9QjNQGcoQD7lJz6VJSDu0LJiqVcbjb0J4EC1XtxbQoKKNucRPfSv9MRzwA15wvYGjjeGEZQapfopv5TlTuQBDI39bONzIqgLGIk+ApjKMF8v1cIxeY2jcYpEbFS87CqzMC3lOQd+ZPxQCeKvJJU7bJQd7w+tVhMKhKPyUrokhl30mzTzqYVyHtdVfiDY+9aJsP2dCohlJmSG5Trn91CBjniGx3LhDzjwjYblwJij3ik/ovPJcONrZQtaf2xbi5W+PONDegtPKFDMdw+jQ0pomrgZizRO00424il+LMufYrvK7vyM3mUWyfFsk7emG0dmc4CB4VyWhdMGamhL14eQBi1U/mPR9v0OCPfnHgI0kP1xVeyQk5EmDcwy8gWduInkuKhLwdfcqZ9VH4vvGq6xmBHdXS2mwqhoJ7OsoDeXgBuk5H3uSrR7UP4=
      on:
        tags: true
