version: "3.7"
services:
  postgres:
    image: makinacorpus/pgrouting:10-2.5-2.6
    environment:
      - POSTGRES_PASSWORD=travis_ci_test
      - POSTGRES_USER=travis_ci_test
      - POSTGRES_DB=travis_ci_test
  web:
    build:
      context: .
    links:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./terra_crud:/code/terra_crud
      - ./test_terra_crud:/code/test_terra_crud
    ports:
      - "8000:8000"
