version: "3"
services:
  postgres:
    image: pgrouting/pgrouting:pgrouting:10-2.5-2.6
    environment:
      - POSTGRES_PASSWORD=travis_ci_test
      - POSTGRES_USER=travis_ci_test
      - POSTGRES_DB=travis_ci_test
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    links:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - DJANGO_SETTINGS_MODULE=test_terra_geocrud.settings.dev
    volumes:
      - .:/code/src
    ports:
      - "8000:8000"
    command: /code/venv/bin/python3.7 ./manage.py runserver 0.0.0.0:8000

volumes:
  postgres:
